---
spring:
  profiles: subject
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
words: Aravind,Saurav,Prudhvi
---
spring:
  profiles: verb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
words: drink,eat,read
---
spring:
  profiles: object
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
words: water,fruit,history
---
spring:
  profiles: sentence
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
