---
spring:
  profiles: object
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8010/eureka/
words: water,fruit,history
---
spring:
  profiles: object-icecream
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8010/eureka/
words: vanilla,pista,chocolate
